
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - app-data:/app/data
    restart: unless-stopped

volumes:
  app-data:
    driver: local
